//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class news_reacts
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> news_id { get; set; }
        public Nullable<int> react_id { get; set; }
    
        public virtual News News { get; set; }
        public virtual React React { get; set; }
        public virtual User User { get; set; }
    }
}
